### PR TITLE
set initial forkid to datastream client

### LINKED ISSUE #601: [RPC] Bali wrong state root after the node is restarted

### PR DESCRIPTION
**Pull request by V-Staykov**
Fixes #601

### CODE REVIEW

File: eth/backend.go [hunk 1]
```diff
@@ -884,8 +884,11 @@ func New(stack *node.Node, config *ethconfig.Config) (*Ethereum, error) {
 			  ZZZZZZZ  K   K  R   R   P       CCCC
 
 			*/
-
-			streamClient := initDataStreamClient(ctx, cfg.Zk)
+			latestForkId, err := stages.GetStageProgress(tx, stages.ForkId)
```
Comment (mandrigin) [inline eth/backend.go:887]: Is stages.ForkId progress guaranteed to be equal to the latest downloaded batch? Is it set in the batches stage?

Comment (V-Staykov) [reply eth/backend.go:887]: yes it is at the end of stage batches

**Review by hexoscott — APPROVED** [review]
