### PR TITLE
faster population of the data stream for consumers

### LINKED ISSUE #555: [Sequencer] Sending txs from RPC on Network 5 intermittent failures
When sending txs using RPC, sometimes the confirmation doesn’t come in time.

We think it could be a regression from the protobuf datastream population.

### PR DESCRIPTION
**Pull request by hexoscott**
Fixes #555

### CODE REVIEW

File: zk/datastream/server/data_stream_server.go [hunk 1]
```diff
@@ -206,78 +205,95 @@ func (srv *DataStreamServer) CreateStreamEntriesProto(
...
-		// could be empty batches in between blocks that could contain ger updates and we need to handle
-		// all of those scenarios
-		entryCount += int(3 * (batchNumber - lastBatchNumber)) // batch bookmark + batch start + batch end
-
-		// we don't write the batch end at the start of the stream when we're sending data to the executor
-		if mode == ExecutorOperationMode {
-			entryCount--
-		}
+
+	batchStart := batchNumber != lastBatchNumber
```
Comment (mandrigin) [inline zk/datastream/server/data_stream_server.go:225]: So we aren’t sending empty batches to the DS even when they are closed?

File: zk/datastream/server/data_stream_server.go [hunk 2]
```diff
@@ -206,78 +205,95 @@ func (srv *DataStreamServer) CreateStreamEntriesProto(
...
-			}
-			fork, err := reader.GetForkId(nextWorkingBatch)
-			if err != nil {
-				return nil, err
-			}
-			batch := srv.CreateBatchStartProto(nextWorkingBatch, srv.chainId, fork, batchType)
-			entries[index] = batch
-			index++
+		// now write in the batch start for this batch
+		batchType := datastream.BatchType_BATCH_TYPE_REGULAR
```
Comment (mandrigin) [inline zk/datastream/server/data_stream_server.go]: Looks like this duplicates with what is within the `for` loop — I would extract a method or a function for that.

File: zk/datastream/server/datastream_populate.go [hunk 3]
```diff
@@ -125,20 +125,22 @@ func WriteBlocksToStream(
...
 
-		gersInBetween, err := reader.GetBatchGlobalExitRootsProto(prevBatchNum, batchNum)
+		nextBatchNum, err := reader.GetBatchNoByL2Block(currentBlockNumber + 1)
 		if err != nil {
 			return err
 		}
 
-		l1InfoMinTimestamps := make(map[uint64]uint64)
+		// a 0 next batch num here would mean we don't know about the next batch so must be at the end of the batch
+		isBatchEnd := nextBatchNum == 0 || nextBatchNum > batchNum
```
Comment (mandrigin) [inline zk/datastream/server/datastream_populate.go]: I wonder if we should have some constant (non 0) for the end of the batch to be returned by GetBatchNoByL2Block. Isn’t batch number 0 a legit batch number?

File: zk/datastream/server/datastream_populate.go [hunk 4]
```diff
@@ -125,20 +125,22 @@ func WriteBlocksToStream(
...
-		// as we're writing to the stream here and not just generating for the executor we want to run in standard mode
-		mode := StandardOperationMode
+		gersInBetween, err := reader.GetBatchGlobalExitRootsProto(prevBatchNum, batchNum)
+		if err != nil {
+			return err
+		}
 
-		// we do not want to force the closing of a batch when writing to the stream - this is only the domain of talking to the executor
-		const forceBatchEnd = false
+		l1InfoMinTimestamps := make(map[uint64]uint64)
```
Comment (mandrigin) [inline zk/datastream/server/datastream_populate.go]: Just have this `make` directly in the call, and also add a comment that this param will be removed in the future version and it is unused.

File: zk/stages/stage_batches.go [hunk 5]
```diff
@@ -256,7 +256,8 @@ LOOP:
 
 			atLeastOneBlockWritten = true
 
-			if l2Block.L2BlockNumber == 0 {
+			// ignore genesis or a repeat of the last block
+			if l2Block.L2BlockNumber == 0 || l2Block.L2BlockNumber == stageProgressBlockNo {
```
Comment (mandrigin) [inline zk/stages/stage_batches.go]: What if we receive older blocks? Should we ignore them too? But maybe with a log warning?

**Review by mandrigin — CHANGES_REQUESTED** [review]
Some feedback is here

File: zk/datastream/server/data_stream_server.go (hunk 1 above)
Comment (hexoscott) [reply zk/datastream/server/data_stream_server.go:225]: We send empty batches by comparing the previous batch with the latest.  So the stream population works on a block basis, so we ask what is batch for block X and what is the batch for block X-1, that will highlight a gap of empty batches which we pick up on later using the `batchGap` loop

Comment (mandrigin) [reply zk/datastream/server/data_stream_server.go:225]: Allright, sure, so no blocks — no stream update.

File: zk/datastream/server/datastream_populate.go (hunk 3 above)
Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: Batch 0 is legit, but it's injected during startup of the node before the chain starts working so it will never be the "next" batch, but signals that we have no data for the batch being queried so we can use it safely to detect the end of the last known batch in the DB

Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: I'm not sure what you mean in the first sentence about the constant non 0

File: zk/datastream/server/datastream_populate.go (hunk 4 above)
Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: I can make it directly in the call, but this is still very much used.  We use it to pass the min timestamps to the executor, without it the calls to it will fail when changes to the l1 info root are present in the batch

File: zk/stages/stage_batches.go (hunk 5 above)
Comment (hexoscott) [reply zk/stages/stage_batches.go]: Yeah that's a fair shout.  I put this in to avoid the unwind, but it would be good to put in a warn for older blocks than expected

File: zk/datastream/server/datastream_populate.go (hunk 3 above)
Comment (mandrigin) [reply zk/datastream/server/datastream_populate.go]: Either return batch -1 and name it a constant like BATCH_NOT_FOUND, or return 0 and also err = ErrNotFound and check for that.

File: zk/datastream/server/datastream_populate.go (hunk 4 above)
Comment (mandrigin) [reply zk/datastream/server/datastream_populate.go]: Ah, that is for the datastream, not for the executor code, sorry then.

File: zk/stages/stage_batches.go (hunk 5 above)
Comment (mandrigin) [reply zk/stages/stage_batches.go]: Yeah, we probably need to split to two things like that:

```		
			if  l2Block.L2BlockNumber == 0 { continue }
			
			if l2Block.L2BlockNumber <= stageProgressBlockNo {
			    Log.Warn(“unexpected block numbers older than progress (received: L2BlockNumber, local: stageProgressBlockNo”)
			    continue
			 }
```

File: zk/datastream/server/data_stream_server.go (hunk 2 above)
Comment (hexoscott) [reply zk/datastream/server/data_stream_server.go]: I'm introducing a type here to track adding entries to the collection to reduce the chance of bugs in the future as well and to have a type we can pass around to functions for this kind of thing

File: zk/datastream/server/datastream_populate.go (hunk 3 above)
Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: got it, thanks for the clarification

Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: I'll use the error approach here as we're dealing with uint and I don't want to use the max value to denote not found

Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: In fact, just a bool `found`, it's not an error

Comment (mandrigin) [reply zk/datastream/server/datastream_populate.go]: Sounds good! I think it is also more in Go-style

Comment (hexoscott) [reply zk/datastream/server/datastream_populate.go]: In fact.... :) this creates quite the large ripple, I think a simple `DoesBatchExist` call is the better option

Comment (mandrigin) [reply zk/datastream/server/datastream_populate.go]: That also works well to me.

File: zk/stages/stage_batches.go (hunk 5 above)
Comment (hexoscott) [reply zk/stages/stage_batches.go]: We expect the latest block to arrive again, this was part of the changes to avoid the unwind, so I have put the warning only for anything older than that

Comment (mandrigin) [reply zk/stages/stage_batches.go]: Ah, okay, sure

Comment (mandrigin) [reply zk/stages/stage_batches.go]: Just make sure you comment the code then, it is not super obvious tbh

**Review by mandrigin — APPROVED** [review]
