### PR TITLE
raised size of memdb

### LINKED ISSUE #911: [RPC] Bali -- can't get witness for batch 55667
from Aggregator

```
10.4.3.56:58460 Processing entry 15123482: error from witness for batch 55667: &{-32000 method handler crashed <nil>}. HALTED!
```

### PR DESCRIPTION
**Pull request by V-Staykov**
- raised memdb limit
 - added error checks

### CODE REVIEW

File: zk/witness/witness.go [hunk 1]
```diff
@@ -187,7 +187,7 @@ func (g *Generator) generateWitness(tx kv.Tx, ctx context.Context, blocks []*eri
 		return nil, fmt.Errorf("block number is in the future latest=%d requested=%d", latestBlock, endBlock)
 	}
 
-	batch := memdb.NewMemoryBatch(tx, g.dirs.Tmp)
+	batch := memdb.NewMemoryBatchWithSize(tx, g.dirs.Tmp, 2*datasize.GB)
```
Comment (mandrigin) [inline zk/witness/witness.go]: Can we do it a command-line flag?

Comment (V-Staykov) [reply zk/witness/witness.go]: Added in the latest commit

**Review by mandrigin — DISMISSED** [review]

**Review by revitteth — APPROVED** [review]
