### PR TITLE
fix datastream block hash

### LINKED ISSUE #559: [RPC] Make a warning if our computed block hash doesn’t match L2 block hash from the datastream
We have L2 block hashes in the datastream now.

When we compute our own block hashes, it would be nice to verify if they match the datastream ones and if they don’t — print a warning to a log, logging datastream block hash, our local block hash and the block number.

### PR DESCRIPTION
**Pull request by V-Staykov**

### CODE REVIEW

File: eth/stagedsync/stage_execute_zkevm.go [hunk 1]
```diff
@@ -121,29 +121,29 @@ Loop:
...
 		//fetch values pre execute
-		preExecuteHeaderHash, block, senders, err := getPreexecuteValues(cfg, ctx, tx, blockNum, prevBlockHash)
+		datastreamBlockHash, block, senders, err := getPreexecuteValues(cfg, ctx, tx, blockNum, prevBlockHash)
 		if err != nil {
 			stoppedErr = err
 			break
 		}
 
-		// Incremental move of next stages depend on fully written ChangeSets, Receipts, CallTraceSet
+		// Incremental move of next stages depend on fulply written ChangeSets, Receipts, CallTraceSet
```
Comment (mandrigin) [inline eth/stagedsync/stage_execute_zkevm.go]: typo

**Review by mandrigin — DISMISSED** [review]
one typo but good overall

**Review by mandrigin — APPROVED** [review]
