### PR TITLE
fix: recover sender only for those txs that are included

### LINKED ISSUE #1605: [Sequencer] performance degraded by sender recovery
A while back we needed to perform sender recovery whilst pulling transactions from the pool to ensure this worked correctly and didn't error before adding the TX to a block.  This looks to have introduced some performance hit to the sequencer which we need to investigate.

Related PR introducing these changes here https://github.com/0xPolygonHermez/cdk-erigon/pull/1480

Things to explore:
- can we avoid sender recovery using the method in the PR?  Maybe get some extra data from the pool for example.
- can we make sender recovery more performant using parallelisation?

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
Performance improvement for cases when due to constraints such as gas limits and counter overflows only a few transactions are included in the block.

For 5000 plain send tx:
original version:
`INFO[01-15|16:03:56.498] Total time to recover sender             total.ms=11457 totalCalls=13342`
fixed version:
`INFO[01-15|15:53:51.740] Total time to recover sender             total.ms=457 totalCalls=5635`

Closes #1605 

NOTE: optimisation of hash calculation will be addressed in #1599

### CODE REVIEW

File: zk/stages/stage_sequence_execute_transactions.go [hunk 1]
```diff
@@ -161,15 +159,26 @@ func attemptAddTransaction(
...
+	if batchDataOverflow && !l1Recovery {
 		log.Debug("Transaction preexecute overflow detected", "txHash", transaction.Hash(), "counters", batchCounters.CombineCollectorsNoChanges().UsedAsString())
 		return nil, nil, overflowCounters, nil
 	}
 
+	if _, ok := transaction.GetSender(); !ok {
+		currentHeight := header.Number.Uint64() - 1
+		sender, err := recoverSender(cfg.chainConfig, transaction, currentHeight)
+		if err != nil {
+			// In this case it will be discarded as Mined, and kept in discardLRU cache
```
Comment (IvanBelyakoff) [inline zk/stages/stage_sequence_execute_transactions.go]: @hexoscott @revitteth is this OK, that it will me discarded like this, or we need some special handling? To discard it differently, we might need to return a discard reason as well and maintain txs with discard reasons to properly discard. On the other hand, I see that we discard txs as due to counters overflow here
`cfg.txPool.MarkForDiscardFromPendingBest` but this is not true.

added to discard list: https://github.com/0xPolygonHermez/cdk-erigon/blob/7a42f3ed3e58e0195d8e9ab072c0a791276044f1/zk/stages/stage_sequence_execute.go#L479

discarded here: https://github.com/0xPolygonHermez/cdk-erigon/blob/7a42f3ed3e58e0195d8e9ab072c0a791276044f1/zk/txpool/pool_zk.go#L320

File: zk/stages/stage_sequence_execute_transactions.go [hunk 2]
```diff
@@ -238,3 +247,9 @@ func attemptAddTransaction(
 
 	return receipt, execResult, overflowNone, nil
 }
+
+func recoverSender(cfg *chain.Config, transaction types.Transaction, blockHeight uint64) (common.Address, error) {
+	cryptoContext := secp256k1.ContextForThread(1)
+	signer := types.MakeSigner(cfg, blockHeight, 0)
+	return signer.SenderWithContext(cryptoContext, transaction)
+}
```
Comment (doutv) [inline zk/stages/stage_sequence_execute_transactions.go]: One question: Why create a `cryptoContext` here? 
We can call `signer.Sender(transaction)`, which would reuse default context and make it a little bit faster

File: zk/stages/stage_sequence_execute_transactions.go (hunk 1 above)
Comment (hexoscott) [reply zk/stages/stage_sequence_execute_transactions.go]: We must discard it at this point as the transaction is invalid.  If we attempt to process it the node will panic later on and we get some strange behaviour for that block.  I'm not sure how these transactions get through the pool but they end up with a sender of 0x0 when they land which isn't right.

Comment (hexoscott) [reply zk/stages/stage_sequence_execute_transactions.go]: @IvanBelyakoff - we need to do this sender recovery check before the call to `attemptAddTransaction`.  Ideally it shouldn't get that far in the process if the sender can't be recovered.

**Review by hexoscott — CHANGES_REQUESTED** [review]
A small change to moving sender recovery to before the call to `attemptAddTransaction`

File: zk/stages/stage_sequence_execute_transactions.go (hunk 1 above)
Comment (IvanBelyakoff) [reply zk/stages/stage_sequence_execute_transactions.go]: I see your point. Since this case is mostly for the counters overflow situation, I wanted to do the recovery of sender after it to save some CPU resources, since it is a rare case AFAIK when sender can't be recovered. If I move to some place before we calculate the counters, then we will do an extra recovery. for every tx that will overflow the counters

Comment (hexoscott) [reply zk/stages/stage_sequence_execute_transactions.go]: OK, the problem is it is fiddly to undo the adding of counters for a single transaction after it has been added this way.  For me it's better to quit early in the process if the sender can't be recovered and not need to deal with unwinding counters after the fact.

Comment (hexoscott) [reply zk/stages/stage_sequence_execute_transactions.go]: There is code in stage_sequence_execute that handles this undoing of counters, so maybe you can send some kind of signal up the stack and deal with it outside of this function?  We just need to be super careful around counters is all.

Comment (IvanBelyakoff) [reply zk/stages/stage_sequence_execute_transactions.go]: I've moved sender recovery outside of addTransaction as you suggested. As we discussed, one downside of this approach is that an extra recovery wil be done for transaction that might not be included, but that is still a great improvement, while we dont mess with counters for now and avoid possible issues. I've created a task to revise the counters processing after we revise batch/block/tx processing.

File: zk/stages/stage_sequence_execute_transactions.go (hunk 2 above)
Comment (IvanBelyakoff) [reply zk/stages/stage_sequence_execute_transactions.go]: Good catch. Initially I avoided to make additional changes due to possible regressions. But I think this one is safe enough.

File: zk/stages/stage_sequence_execute_transactions.go [hunk 3]
```diff
@@ -149,6 +137,14 @@ func attemptAddTransaction(
 
 	txCounters := vm.NewTransactionCounter(transaction, sdb.smt.GetDepth(), uint16(forkId), cfg.zk.VirtualCountersSmtReduction, cfg.zk.ShouldCountersBeUnlimited(l1Recovery))
 	overflow, err = batchCounters.AddNewTransactionCounters(txCounters)
+	if err != nil {
+		if overflow && !l1Recovery {
```
Comment (hexoscott) [inline zk/stages/stage_sequence_execute_transactions.go]: we need to check the `overflow` bool outside of the `err` check.  An overflow might not trigger an error state and we'll miss it when we need to handle it.

**Review by hexoscott — CHANGES_REQUESTED** [review]

File: zk/stages/stage_sequence_execute_transactions.go (hunk 3 above)
Comment (IvanBelyakoff) [reply zk/stages/stage_sequence_execute_transactions.go]: I reverted this part

**Review by hexoscott — APPROVED** [review]

**Comment by zjg555543** [comment]
Is it will still slow especially for ERC20 or ETH txs, since each batch can include 700+ transactions because it uses serial mode?

**Comment by IvanBelyakoff** [comment]
> Is it will still slow especially for ERC20 or ETH txs, since each batch can include 700+ transactions because it uses serial mode?

This PR optimises sender recovery to avoid it for txs that will no be included. But I can not do that in parallel:
1) AFAIK we can't know if tx counters will overflow in advance so we need to add transactions one by one, recovering the sender before that.
2) Even if we could do that in parallel, that would not necessarily give any performance improvement and could actually produce the opposite effect, just like when I did some profiling with parallel hash calculation
