### PR TITLE
fix: no resequence if l1 sync enabled

### LINKED ISSUE #1574: Unable to recover from L1 after unwinding
After a sequencer is unwound to a previous block, we are not able to recover it from L1, and it will get stuck in a loop "The node need re-sequencing but this option is disabled" (see attached screenshot). 

I think the problem is that the datastream is ahead of db after unwinding, and when the node restarts, it will try to re-sequence after observing the difference of block tip between the ds and db. 

image

### PR DESCRIPTION
**Pull request by V-Staykov**

### CODE REVIEW

**Review by revitteth — APPROVED** [review]

File: zk/stages/stage_sequence_execute.go [hunk 1]
```diff
@@ -47,7 +47,12 @@ func SpawnSequencingStage(
 	}
 
 	if lastBatch < highestBatchInDs {
-		return resequence(s, u, ctx, cfg, historyCfg, lastBatch, highestBatchInDs)
+		if err = cfg.dataStreamServer.UnwindToBatchStart(lastBatch + 1); err != nil {
+			return err
+		}
```
Comment (cffls) [inline zk/stages/stage_sequence_execute.go:52]: Is this going to work in resequence mode? We retrieve the data to be resequenced from ds. If ds is unwound, we won't have anything to resequence.

Comment (revitteth) [reply zk/stages/stage_sequence_execute.go:52]: We should flag activate the ability to resequence from the ds? This behaviour is needed when l1 recovering - are both scenarios valid simultaneously?

Comment (cffls) [reply zk/stages/stage_sequence_execute.go:52]: Yes, we should read data from ds when resequencing, but only one mode (from `resequence`, `l1recover`, `limbo`, `sequence`) can be activated at one time.
Looks like resequencing is broken in the [latest CI](https://github.com/0xPolygonHermez/cdk-erigon/actions/runs/12392908558/job/34593069054#step:4:192) and also in [this PR](https://github.com/0xPolygonHermez/cdk-erigon/actions/runs/12392908558/job/34593069054#step:4:192), but somehow the CI job didn't expose the error.
